http:
  middlewares:
    SecHeaders:
      headers:
        customResponseHeaders:
        Permissions-Policy: "geolocation=(self), microphone=(), camera=(), fullscreen=*" 
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
