version: '3.7'

services:
  db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    environment:
      MARIADB_ROOT_PASSWORD_FILE: '/run/secrets/mariadb-root-password'
      MARIADB_USER_FILE: '/run/secrets/mariadb-user'
      MARIADB_DATABASE_FILE: '/run/secrets/mariadb-database'
      MARIADB_PASSWORD_FILE: '/run/secrets/mariadb-password'
    secrets:
      - mariadb-root-password
      - mariadb-user
      - mariadb-database
      - mariadb-password
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - db
    image: nextcloud
    restart: unless-stopped
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER_FILE: '/run/secrets/mariadb-user'
      MYSQL_DATABASE_FILE: '/run/secrets/mariadb-database'
      MYSQL_PASSWORD_FILE: '/run/secrets/mariadb-password'
      NEXTCLOUD_ADMIN_PASSWORD_FILE: '/run/secrets/nextcloud-admin-password'
      NEXTCLOUD_ADMIN_USER_FILE: '/run/secrets/nextcloud-admin-user'
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_URL}
    secrets:
      - mariadb-user
      - mariadb-database
      - mariadb-password
      - nextcloud-admin-user
      - nextcloud-admin-password
    networks:
      - lan
      - traefik_web
    volumes:
      - nextcloud:/var/www/html
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: 'Host(`${NEXTCLOUD_URL}`)'
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: myresolver


volumes:
  nextcloud:
  db:

networks:
  traefik_web:
    external: true
  lan:

secrets:
  mariadb-user:
    file: ./secrets/mariadb-user.txt
  mariadb-database:
    file: ./secrets/mariadb-database.txt
  mariadb-password:
    file: ./secrets/mariadb-password.txt
  mariadb-root-password:
    file: ./secrets/mariadb-root-password.txt
  nextcloud-admin-user:
    file: ./secrets/nextcloud-admin-user.txt
  nextcloud-admin-password:
    file: ./secrets/nextcloud-admin-password.txt
